### ISSUE TITLE
运行报错，请问如何解决呢？

### ISSUE THREAD

**Issue by green-l** [xiaoyu1233/mmdetection2.0_visualize#3]
python tools/voc_eval_visualize.py /root/mmdetection/eval/result.pkl  ./configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py
270 270
Traceback (most recent call last):
  File "tools/voc_eval_visualize.py", line 45, in <module>
    main()
  File "tools/voc_eval_visualize.py", line 41, in main
    voc_eval(args.result, test_dataset, args.iou_thr)
  File "tools/voc_eval_visualize.py", line 25, in voc_eval
    nproc=nproc)
  File "/root/mmdetection/mmdet/core/evaluation/mean_ap_visualize.py", line 418, in eval_map
    plt.savefig('./mmdetection/PR_Curve_each_class.png')
  File "/home/lulu/anaconda3/envs/open-mmlabb/lib/python3.7/site-packages/matplotlib/pyplot.py", line 937, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/lulu/anaconda3/envs/open-mmlabb/lib/python3.7/site-packages/matplotlib/figure.py", line 2962, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/lulu/anaconda3/envs/open-mmlabb/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2261, in print_figure
    **kwargs)
  File "/home/lulu/anaconda3/envs/open-mmlabb/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 1669, in wrapper
    return func(*args, **kwargs)
  File "/home/lulu/anaconda3/envs/open-mmlabb/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 511, in print_png
    dpi=self.figure.dpi, metadata=metadata, pil_kwargs=pil_kwargs)
  File "/home/lulu/anaconda3/envs/open-mmlabb/lib/python3.7/site-packages/matplotlib/image.py", line 1616, in imsave
    image.save(fname, **pil_kwargs)
  File "/home/lulu/anaconda3/envs/open-mmlabb/lib/python3.7/site-packages/PIL/Image.py", line 2169, in save
    fp = builtins.open(filename, "w+b")
**FileNotFoundError: [Errno 2] No such file or directory: './mmdetection/PR_Curve_each_class.png'**

**Comment by lijf138** [comment]
我和楼上报一样的错误阿？不知道如何解决？

**Comment by lijf138** [comment]
I made the same mistake，too

**Comment by so-bright** [comment]
请问，这个错误解决了吗
